version: '3.4'

services:
  incrementapi:
    image: incrementapi:latest
    build:
      context: ../IncrementApi
      dockerfile: Dockerfile
    ports:
      - "5211:80"

  callerapi:
    image: callerapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IncrementApiUrl=http://incrementapi/api/counter
    ports:
      - "5245:80"
